version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: trading-app
    volumes:
      - .:/app
    ports:
      - "8501:8501"  
    command: bash

  airflow:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: airflow
    restart: always
    environment:
      - AIRFLOW__CORE__EXECUTOR=SequentialExecutor
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=sqlite:////root/airflow/airflow.db
      - PYTHONPATH=/app
    volumes:
      - .:/app
    ports:
      - "8090:8080" 
    command: >
      bash -c "
        airflow db init &&
        airflow users create --username admin --password admin --firstname Carolina --lastname Admin --role Admin --email admin@example.com &&
        airflow scheduler &
        airflow webserver
      "